name: DayFlow
options:
  minimumXcodeGenVersion: 2.38.0
schemes:
  DayFlow:
    build:
      targets:
        DayFlow: all
    test:
      targets:
        - DayFlowTests
targets:
  DayFlow:
    type: application
    supportedDestinations: [iOS, iOS Simulator]
    deploymentTarget: "17.5"
    sources:
      - DayFlow
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.kakaoent.dayflow
        SWIFT_VERSION: 6.0
        GENERATE_INFOPLIST_FILE: YES
        INFOPLIST_KEY_UILaunchScreen_Generation: YES
        INFOPLIST_KEY_UIApplicationSceneManifest_Generation: YES
        INFOPLIST_KEY_UIApplicationSupportsIndirectInputEvents: YES
  DayFlowTests:
    type: bundle.unit-test
    supportedDestinations: [iOS, iOS Simulator]
    deploymentTarget: "17.5"
    sources:
      - DayFlowTests
    dependencies:
      - target: DayFlow
    settings:
      base:
        GENERATE_INFOPLIST_FILE: YES
        SWIFT_VERSION: 6.0
