name: DayFlow
options:
  minimumXcodeGenVersion: 2.45.3
schemes:
  DayFlow:
    build:
      targets:
        DayFlow: all
    test:
      targets:
        - DayFlowTests
        - DayFlowUITests
targets:
  DayFlow:
    type: application
    supportedDestinations: [iOS, iOS Simulator]
    deploymentTarget: "17.5"
    sources:
      - DayFlow
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.kakaoent.dayflow
        SWIFT_VERSION: 6.0
      configs:
        Debug:
          INFOPLIST_FILE: DayFlow/Info-Debug.plist
        Release:
          INFOPLIST_FILE: DayFlow/Info-Release.plist
  DayFlowTests:
    type: bundle.unit-test
    supportedDestinations: [iOS, iOS Simulator]
    deploymentTarget: "17.5"
    sources:
      - DayFlowTests
    dependencies:
      - target: DayFlow
    settings:
      base:
        GENERATE_INFOPLIST_FILE: YES
        SWIFT_VERSION: 6.0
  DayFlowUITests:
    type: bundle.ui-testing
    supportedDestinations: [iOS, iOS Simulator]
    deploymentTarget: "17.5"
    sources:
      - DayFlowUITests
    dependencies:
      - target: DayFlow
    settings:
      base:
        GENERATE_INFOPLIST_FILE: YES
        SWIFT_VERSION: 6.0
